# Generated by Django 5.1.4 on 2024-12-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=600)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', models.ImageField(upload_to='')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataUpdate', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurante.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
            },
        ),
    ]
