# Generated by Django 5.1.4 on 2024-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='descricao',
            field=models.CharField(max_length=600, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Imagem do Item'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
    ]
