# Generated by Django 5.1.4 on 2024-12-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_cardapio_descricao_alter_cardapio_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardapio',
            options={'verbose_name': 'Cardápio'},
        ),
    ]
