# Generated by Django 5.1.4 on 2024-12-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_cardapio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardapio',
            options={'verbose_name': 'Cardápio', 'verbose_name_plural': 'Cardápio'},
        ),
    ]
