# Generated by Django 5.1.4 on 2024-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_cardapio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Imagem do Item'),
        ),
    ]
