# Generated by Django 5.1.4 on 2024-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numPessoas',
            field=models.IntegerField(verbose_name='Número de Pessoas'),
        ),
    ]
