# Generated by Django 5.1.4 on 2024-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_alter_reserva_numpessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(help_text='(00) 90000 - 0000', max_length=17, unique=True, verbose_name='Telefone'),
        ),
    ]
